-- ═══════════════════════════════════════════════════════════════════════════
-- Willow Weave — complete schema (run once against a fresh Supabase project)
-- Apply via: Supabase Dashboard → SQL Editor → paste & run,
--        or: supabase db push (with the CLI linked to your project)
-- ═══════════════════════════════════════════════════════════════════════════

create extension if not exists pg_trgm;

-- ── Staff / roles ────────────────────────────────────────────────────────────
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  name text not null default '',
  role text not null default 'staff' check (role in ('owner', 'staff')),
  created_at timestamptz not null default now()
);

-- Helper used by RLS policies: is the current user staff (any role)?
create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as
$$ select exists (select 1 from profiles where id = auth.uid()); $$;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public as
$$ select exists (select 1 from profiles where id = auth.uid() and role = 'owner'); $$;

-- ── Catalog ──────────────────────────────────────────────────────────────────
create table public.collections (
  id bigint generated by default as identity primary key,
  handle text not null unique,
  title text not null,
  description_html text not null default '',
  image_url text,
  "group" text not null default 'fabrics' check ("group" in ('volumes','occasions','pieces','fabrics')),
  position int not null default 0,
  featured boolean not null default false,
  published boolean not null default true
);

create table public.size_charts (
  id bigint generated by default as identity primary key,
  name text not null,
  applies_to text not null default '',
  columns jsonb not null default '[]',
  rows jsonb not null default '[]',
  note text not null default ''
);

create table public.products (
  id bigint generated by default as identity primary key,
  handle text not null unique,
  title text not null,
  description_html text not null default '',
  product_type text not null default '',
  fabrics text[] not null default '{}',
  tags text[] not null default '{}',
  vendor text not null default 'Willow Weave',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  size_chart_id bigint references size_charts (id) on delete set null,
  search tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(product_type, '')), 'B') ||
    setweight(to_tsvector('simple', array_to_string(tags, ' ')), 'B') ||
    setweight(to_tsvector('simple', array_to_string(fabrics, ' ')), 'B') ||
    setweight(to_tsvector('simple', coalesce(description_html, '')), 'C')
  ) stored
);
create index products_search_idx on public.products using gin (search);
create index products_title_trgm_idx on public.products using gin (title gin_trgm_ops);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  url text not null,
  alt text not null default '',
  width int,
  height int,
  position int not null default 0
);
create index product_images_product_idx on public.product_images (product_id, position);

create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products (id) on delete cascade,
  title text not null default '',
  size text,
  color text,
  price numeric(12,2) not null check (price >= 0),
  compare_at_price numeric(12,2) check (compare_at_price is null or compare_at_price >= 0),
  stock int not null default 0 check (stock >= 0),
  sku text,
  position int not null default 0
);
create index product_variants_product_idx on public.product_variants (product_id, position);

create table public.product_collections (
  product_id bigint not null references products (id) on delete cascade,
  collection_id bigint not null references collections (id) on delete cascade,
  position int not null default 0,
  primary key (product_id, collection_id)
);
create index product_collections_collection_idx on public.product_collections (collection_id, position);

-- ── Discounts ────────────────────────────────────────────────────────────────
create table public.discount_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('percent','fixed')),
  value numeric(12,2) not null check (value > 0),
  min_subtotal numeric(12,2) not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit int,
  times_used int not null default 0,
  active boolean not null default true
);

-- ── Orders ───────────────────────────────────────────────────────────────────
create sequence public.order_number_seq start 1001;

create table public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique default ('WW-' || nextval('public.order_number_seq')),
  status text not null default 'pending'
    check (status in ('pending','confirmed','shipped','delivered','cancelled')),
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  city text not null,
  notes text,
  payment_method text not null default 'cod',
  subtotal numeric(12,2) not null,
  discount_code text,
  discount_amount numeric(12,2) not null default 0,
  shipping_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null,
  internal_notes text,
  status_history jsonb not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index orders_status_idx on public.orders (status, created_at desc);
create index orders_created_idx on public.orders (created_at desc);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders (id) on delete cascade,
  product_id bigint,
  variant_id bigint,
  handle text not null default '',
  title text not null,
  size text,
  color text,
  unit_price numeric(12,2) not null,
  quantity int not null check (quantity > 0),
  image_url text
);
create index order_items_order_idx on public.order_items (order_id);

-- ── Settings (singleton row, id always 1) ────────────────────────────────────
create table public.store_settings (
  id int primary key default 1 check (id = 1),
  store_name text not null default 'Willow Weave',
  shipping_fee numeric(12,2) not null default 0,
  free_shipping_threshold numeric(12,2),
  notify_email text not null default '',
  announcement text
);
insert into public.store_settings (id) values (1);

-- ═══════════════════════════════════════════════════════════════════════════
-- place_order: the ONLY write path for checkout. Server-side price + stock
-- validation, atomic stock decrement, discount application.
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.place_order(
  p_customer_name text,
  p_phone text,
  p_email text,
  p_address text,
  p_city text,
  p_notes text,
  p_discount_code text,
  p_items jsonb -- [{"variant_id":1,"quantity":2}]
) returns jsonb
language plpgsql security definer set search_path = public as
$$
declare
  v_item record;
  v_variant record;
  v_product record;
  v_subtotal numeric(12,2) := 0;
  v_discount discount_codes%rowtype;
  v_discount_amount numeric(12,2) := 0;
  v_settings store_settings%rowtype;
  v_shipping numeric(12,2);
  v_order_id bigint;
  v_order_number text;
  v_image text;
begin
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'EMPTY_CART';
  end if;

  select * into v_settings from store_settings where id = 1;

  -- Lock + validate every variant, compute subtotal from DB prices
  for v_item in select (e->>'variant_id')::bigint as variant_id, (e->>'quantity')::int as quantity
                from jsonb_array_elements(p_items) e
  loop
    if v_item.quantity is null or v_item.quantity < 1 or v_item.quantity > 20 then
      raise exception 'BAD_QUANTITY';
    end if;
    select * into v_variant from product_variants where id = v_item.variant_id for update;
    if not found then raise exception 'VARIANT_NOT_FOUND:%', v_item.variant_id; end if;
    select * into v_product from products where id = v_variant.product_id;
    if v_product.published_at is null then raise exception 'PRODUCT_UNAVAILABLE:%', v_product.handle; end if;
    if v_variant.stock < v_item.quantity then
      raise exception 'INSUFFICIENT_STOCK:%:%', v_product.title,
        coalesce(v_variant.size, v_variant.title);
    end if;
    v_subtotal := v_subtotal + v_variant.price * v_item.quantity;
  end loop;

  -- Discount
  if p_discount_code is not null and length(trim(p_discount_code)) > 0 then
    select * into v_discount from discount_codes
      where upper(code) = upper(trim(p_discount_code)) for update;
    if not found or not v_discount.active
       or (v_discount.starts_at is not null and now() < v_discount.starts_at)
       or (v_discount.ends_at is not null and now() > v_discount.ends_at)
       or (v_discount.usage_limit is not null and v_discount.times_used >= v_discount.usage_limit)
       or v_subtotal < v_discount.min_subtotal then
      raise exception 'INVALID_DISCOUNT';
    end if;
    if v_discount.type = 'percent' then
      v_discount_amount := round(v_subtotal * v_discount.value / 100, 2);
    else
      v_discount_amount := least(v_discount.value, v_subtotal);
    end if;
    update discount_codes set times_used = times_used + 1 where id = v_discount.id;
  end if;

  -- Shipping
  v_shipping := coalesce(v_settings.shipping_fee, 0);
  if v_settings.free_shipping_threshold is not null
     and (v_subtotal - v_discount_amount) >= v_settings.free_shipping_threshold then
    v_shipping := 0;
  end if;

  insert into orders (customer_name, phone, email, address, city, notes,
                      subtotal, discount_code, discount_amount, shipping_fee, total,
                      status_history)
  values (p_customer_name, p_phone, nullif(trim(coalesce(p_email,'')), ''), p_address, p_city, p_notes,
          v_subtotal,
          case when v_discount_amount > 0 then upper(trim(p_discount_code)) else null end,
          v_discount_amount, v_shipping,
          v_subtotal - v_discount_amount + v_shipping,
          jsonb_build_array(jsonb_build_object('status','pending','at', now())))
  returning id, order_number into v_order_id, v_order_number;

  -- Items (snapshot) + stock decrement
  for v_item in select (e->>'variant_id')::bigint as variant_id, (e->>'quantity')::int as quantity
                from jsonb_array_elements(p_items) e
  loop
    select v.*, p.title as product_title, p.handle as product_handle
      into v_variant
      from product_variants v join products p on p.id = v.product_id
      where v.id = v_item.variant_id;
    select url into v_image from product_images
      where product_id = v_variant.product_id order by position limit 1;
    insert into order_items (order_id, product_id, variant_id, handle, title, size, color,
                             unit_price, quantity, image_url)
    values (v_order_id, v_variant.product_id, v_item.variant_id, v_variant.product_handle,
            v_variant.product_title, v_variant.size, v_variant.color,
            v_variant.price, v_item.quantity, v_image);
    update product_variants set stock = stock - v_item.quantity where id = v_item.variant_id;
  end loop;

  return jsonb_build_object(
    'order_number', v_order_number,
    'total', v_subtotal - v_discount_amount + v_shipping
  );
end;
$$;

-- Validate a discount code for the cart page (read-only preview)
create or replace function public.preview_discount(p_code text, p_subtotal numeric)
returns jsonb language plpgsql stable security definer set search_path = public as
$$
declare v discount_codes%rowtype; v_amount numeric(12,2);
begin
  select * into v from discount_codes where upper(code) = upper(trim(p_code));
  if not found or not v.active
     or (v.starts_at is not null and now() < v.starts_at)
     or (v.ends_at is not null and now() > v.ends_at)
     or (v.usage_limit is not null and v.times_used >= v.usage_limit)
     or p_subtotal < v.min_subtotal then
    return jsonb_build_object('valid', false);
  end if;
  if v.type = 'percent' then v_amount := round(p_subtotal * v.value / 100, 2);
  else v_amount := least(v.value, p_subtotal); end if;
  return jsonb_build_object('valid', true, 'amount', v_amount, 'code', v.code);
end;
$$;

-- ── Row Level Security ───────────────────────────────────────────────────────
alter table public.profiles enable row level security;
alter table public.collections enable row level security;
alter table public.size_charts enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_collections enable row level security;
alter table public.discount_codes enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_settings enable row level security;

-- Public (anon) read of the published catalog
create policy "public read collections" on public.collections for select using (published or is_staff());
create policy "public read products" on public.products for select using (published_at is not null or is_staff());
create policy "public read images" on public.product_images for select using (true);
create policy "public read variants" on public.product_variants for select using (true);
create policy "public read memberships" on public.product_collections for select using (true);
create policy "public read size charts" on public.size_charts for select using (true);
create policy "public read settings" on public.store_settings for select using (true);

-- Staff write access to catalog + settings + discounts
create policy "staff write collections" on public.collections for all using (is_staff()) with check (is_staff());
create policy "staff write products" on public.products for all using (is_staff()) with check (is_staff());
create policy "staff write images" on public.product_images for all using (is_staff()) with check (is_staff());
create policy "staff write variants" on public.product_variants for all using (is_staff()) with check (is_staff());
create policy "staff write memberships" on public.product_collections for all using (is_staff()) with check (is_staff());
create policy "staff write size charts" on public.size_charts for all using (is_staff()) with check (is_staff());
create policy "staff write settings" on public.store_settings for update using (is_staff()) with check (is_staff());

-- Discounts: staff only (customers never list codes; validation goes through RPCs)
create policy "staff read discounts" on public.discount_codes for select using (is_staff());
create policy "staff write discounts" on public.discount_codes for all using (is_staff()) with check (is_staff());

-- Orders: staff only (checkout inserts happen inside place_order, security definer)
create policy "staff read orders" on public.orders for select using (is_staff());
create policy "staff update orders" on public.orders for update using (is_staff()) with check (is_staff());
create policy "staff read order items" on public.order_items for select using (is_staff());

-- Profiles: staff can see the staff list; owners manage it
create policy "staff read profiles" on public.profiles for select using (is_staff());
create policy "owner write profiles" on public.profiles for all using (is_owner()) with check (is_owner());

-- Allow anon execution of the checkout + discount preview RPCs only
revoke all on function public.place_order from public;
revoke all on function public.preview_discount from public;
grant execute on function public.place_order to anon, authenticated, service_role;
grant execute on function public.preview_discount to anon, authenticated, service_role;

-- ── Seeding helper: after inserting rows with explicit ids, bump the identity
-- sequences so future inserts don't collide. Service-role only.
create or replace function public.reset_id_sequences()
returns void language plpgsql security definer set search_path = public as
$$
begin
  perform setval(pg_get_serial_sequence('products', 'id'), greatest((select coalesce(max(id), 1) from products), 1));
  perform setval(pg_get_serial_sequence('product_variants', 'id'), greatest((select coalesce(max(id), 1) from product_variants), 1));
  perform setval(pg_get_serial_sequence('product_images', 'id'), greatest((select coalesce(max(id), 1) from product_images), 1));
  perform setval(pg_get_serial_sequence('collections', 'id'), greatest((select coalesce(max(id), 1) from collections), 1));
  perform setval(pg_get_serial_sequence('size_charts', 'id'), greatest((select coalesce(max(id), 1) from size_charts), 1));
end;
$$;
revoke all on function public.reset_id_sequences from public;
grant execute on function public.reset_id_sequences to service_role;

-- ── Typo-tolerant catalog search (used when Supabase mode is active) ─────────
create or replace function public.search_products(q text, max_results int default 12)
returns table (id bigint, handle text, title text, rank real)
language sql stable security definer set search_path = public as
$$
  select p.id, p.handle, p.title,
         (ts_rank(p.search, websearch_to_tsquery('simple', q)) +
          similarity(p.title, q))::real as rank
  from products p
  where p.published_at is not null
    and (p.search @@ websearch_to_tsquery('simple', q) or p.title % q)
  order by rank desc
  limit max_results;
$$;
grant execute on function public.search_products to anon, authenticated, service_role;
